### ISSUE TITLE
Purpose of this repository

### ISSUE THREAD

**Issue by kizule** [kizule/hacktoberfest-2021#4]
As README.md is a bit unclear, give me ideas what should be done here, like adding "hello world" programs in different programming languages and etc.

**Comment by kizule** [comment]
@realkelvinperez do you have any ideas? :)

**Comment by realkelvinperez** [comment]
Well that isn't a bad idea. you could also have people just input there first snippets in whatever programming language that they love. Since this repo is an easy PR that would be something easy to do. i also saw another repo where people would submit pictures of there code and they would post it up on the frontend 

What direction do you want to take it in?

**Comment by kizule** [comment]
Thanks @realkelvinperez for sharing your opinion. I think that "putting first snippets in whatever programming language" would be great.

Would you like to fix my README.md file? 😄 Also, I think that for contributors we should use CONTRIBUTORS.md file.

**Comment by avyayjain** [comment]
I have an idea that we can add different types of projects to this repository in different languages

**Comment by kizule** [comment]
Thanks for the ideas! I'm closing this issue, and I want you everyone a good luck in participating. :)
